# Generated by Django 4.1.5 on 2023-02-12 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TV',
        ),
        migrations.AddField(
            model_name='movie',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.account'),
            preserve_default=False,
        ),
    ]
